name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Mdbook
      run:  cargo install mdbook --version 0.3.7 && cargo install mdbook-linkcheck --version 0.5.0
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Build
      run: mdbook build
    - name: Deploy to pages
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: awb-pw/deploy-to-github-pages-action@1.1.1
      env:
        AUTHOR: crlf0710
        BUILD_PATH: build
        GITHUB_PAGE_NAME: SciADV-cn
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
        USERNAME: crlf0710
        EMAIL: crlf0710@gmail.com
