name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz | tar xz
        # Add the book directory to the $PATH
        echo "::add-path::$GITHUB_WORKSPACE"
    - name: Install mdbook-toc
      run: curl -L https://github.com/badboy/mdbook-toc/releases/download/0.2.4/mdbook-toc-0.2.4-x86_64-unknown-linux-gnu.tar.gz | tar xz
  
    - name: Install mdbook-mermaid
      run: curl -L https://github.com/badboy/mdbook-mermaid/releases/download/0.2.2/mdbook-mermaid-0.2.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
    - name: Build
      run: |
        mdbook build
        touch book/.nojekyll
    - name: Deploy to pages
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.PA }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: book # The folder the action should deploy.      
